file_format: "1"
id: exkeylibur
name: Exkeylibur
type: shield
url: https://github.com/tlietz/Exkeylibur
requires: [pro_micro]
exposes: []
features:
    - keys
siblings:
    - exkeylibur_left
    - exkeylibur_right
